# Generated by Django 5.1.6 on 2025-03-06 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0002_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_content',
        ),
        migrations.AlterField(
            model_name='chirp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
