# Generated by Django 5.1.6 on 2025-03-06 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0003_remove_reply_reply_content_alter_chirp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
